name: Trigger auto deployment for springbootappnameprop

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/springbootappnameprop-AutoDeployTrigger-608bef17-fe11-4430-9936-6f4d59216506.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Update db url
        run: sed -i 's/<app_name>/${{ secrets.app_name }}/' src/main/resources/application.properties

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SPRINGBOOTAPPNAMEPROP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SPRINGBOOTAPPNAMEPROP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SPRINGBOOTAPPNAMEPROP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.SPRINGBOOTAPPNAMEPROP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SPRINGBOOTAPPNAMEPROP_REGISTRY_PASSWORD }}
          containerAppName: springbootappnameprop
          resourceGroup: rgcontappdemo
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


